### ISSUE TITLE
Parte 02 - Corrigir saldo sendo pedido duas vezes

### ISSUE THREAD

**Issue by leodavidbr** [Gerencia-de-configuracao-e-mudancas-ALN/GCM-Sistema-Bancario#45]
- [x] Identificar causa do erro no front, onde o saldo está sendo pedido duas vezes ao cadastrar a conta (na conta normal e na conta poupança)
- [x] Corrigir o erro

## OBS:
- As alterações devem ser feitas em branch feature e "mergeadas" na develop

**Comment by neylanepl** [comment]
- O erro aconteceu no commit [fix: merge com develop](https://github.com/Gerencia-de-configuracao-e-mudancas-ALN/GCM-Sistema-Bancario/commit/34d1fee3296cc8f73c114a76462b8d0cf2b3aa2d), onde deveria pedir o saldo inicial apenas para as contas normal e poupança, para conta bônus não é necessário
